
#ifndef STATE_CONTROL_GORILLA_H
#define STATE_CONTROL_GORILLA_H

/*
 *  ====== GORILLA'S ANIMATIONS ======
 */
#define TR_ANIMATION_GORILLA_STAY 0
#define TR_ANIMATION_GORILLA_ARRRR 1
#define TR_ANIMATION_GORILLA_STAY_ATTACK 2
#define TR_ANIMATION_GORILLA_DEAD1 7 // fall front
#define TR_ANIMATION_GORILLA_DEAD2 8 // fall back
#define TR_ANIMATION_GORILLA_CLIMB 19 // 512

//   ====== GORILLA'S STATES ======
#define TR_STATE_GORILLA_STAY 1  // -> 3 -> 4 -> 6 -> 7 -> 8 -> 9 -> 10
#define TR_STATE_GORILLA_RUN 3 // -> 1
#define TR_STATE_GORILLA_FORWARD_ATTACK 4
#define TR_STATE_GORILLA_DEAD 5
#define TR_STATE_GORILLA_ARRRR 6
#define TR_STATE_GORILLA_STAY_ATTACK 7
#define TR_STATE_GORILLA_STRAFE_LEFT 8 // -> 1
#define TR_STATE_GORILLA_STRAFE_RIGHT 9 // -> 1
#define TR_STATE_GORILLA_JUMP 10
#define TR_STATE_GORILLA_CLIMB 11

#endif

