#ifndef H_STATE_CONTROL_TIGER_H
#define H_STATE_CONTROL_TIGER_H

// Tiger animations
#define TR_ANIMATION_TIGER_RUN 0
#define TR_ANIMATION_TIGER_STAY_ATTACK 1
#define TR_ANIMATION_TIGER_JUMP_ATTACK 2
#define TR_ANIMATION_TIGER_ROAR_1 3
#define TR_ANIMATION_TIGER_ROAR_2 4
#define TR_ANIMATION_TIGER_STAY 7
#define TR_ANIMATION_TIGER_WALK 8
#define TR_ANIMATION_TIGER_DEAD 11


// Tiger states
#define TR_STATE_TIGER_DEAD 0
#define TR_STATE_TIGER_STAY 1
#define TR_STATE_TIGER_WALK 2
#define TR_STATE_TIGER_RUN 3
#define TR_STATE_TIGER_ROAR_1 5
#define TR_STATE_TIGER_STAY_ATTACK 6
#define TR_STATE_TIGER_JUMP_ATTACK 7
#define TR_STATE_TIGER_ROAR_2 8

#endif
