
#ifndef STATE_CONTROL_SKATEBOARDIST_H
#define STATE_CONTROL_SKATEBOARDIST_H

/*
 *  ====== SKATEBOARDIST'S ANIMATIONS ======
 */

#define TR_ANIMATION_SKATEBOARDIST_STAY 7
#define TR_ANIMATION_SKATEBOARDIST_SHOOTING1 10
#define TR_ANIMATION_SKATEBOARDIST_SHOOTING2 11
#define TR_ANIMATION_SKATEBOARDIST_DEAD 13

//   ====== SKATEBOARDIST'S STATES ======
#define TR_STATE_SKATEBOARDIST_STOP 0   // -> 1 -> 2
#define TR_STATE_SKATEBOARDIST_SHOOTING1 1
#define TR_STATE_SKATEBOARDIST_INERTIA 2  // -> 0 -> 3 -> 4
#define TR_STATE_SKATEBOARDIST_RIDE 3   // -> 2
#define TR_STATE_SKATEBOARDIST_SHOOTING2 4
#define TR_STATE_SKATEBOARDIST_DEAD 5

#endif

