
#ifndef STATE_CONTROL_WINGED_MUTANT_H
#define STATE_CONTROL_WINGED_MUTANT_H

/*
 *  ====== WINGED_MUTANT'S ANIMATIONS ======
 */
#define TR_ANIMATION_WINGED_MUTANT_STAY_INIT 0
#define TR_ANIMATION_WINGED_MUTANT_STAY 2
#define TR_ANIMATION_WINGED_MUTANT_FLY 24

//   ====== WINGED_MUTANT'S STATES ======
#define TR_STATE_WINGED_MUTANT_STAY 1 // -> 3 -> 4 -> 6 -> 8 -> 9 -> 10 -> 13
#define TR_STATE_WINGED_MUTANT_STAY_INIT 12  // -> 1
#define TR_STATE_WINGED_MUTANT_WALK 2  // -> 1 -> 6
#define TR_STATE_WINGED_MUTANT_RUN 3   // -> 1 -> 7
#define TR_STATE_WINGED_MUTANT_JUMP_ATTACK 4
#define TR_STATE_WINGED_MUTANT_STAY_ALERT 6 // -> 1 -> 2
#define TR_STATE_WINGED_MUTANT_RUN_ATTACK 7
#define TR_STATE_WINGED_MUTANT_STAY_ATTACK 8
#define TR_STATE_WINGED_MUTANT_STAY_FAST_SHOOT 9 // -> 1 -> 11
#define TR_STATE_WINGED_MUTANT_STAY_AIM 10 // -> 1 -> 11
#define TR_STATE_WINGED_MUTANT_STAY_SHOOT 11
#define TR_STATE_WINGED_MUTANT_FLY 13 // -> 1

#endif

