
#ifndef STATE_CONTROL_WOLF_H
#define STATE_CONTROL_WOLF_H

/*
 *  ====== WOLF'S ANIMATIONS ======
 */
#define TR_ANIMATION_WOLF_STAY_TO_IDLE 0
#define TR_ANIMATION_WOLF_IDLE_TO_STAY 1
#define TR_ANIMATION_WOLF_START_WALK 2
#define TR_ANIMATION_WOLF_WALK 3
#define TR_ANIMATION_WOLF_WALK_TO_CROUCH 4
#define TR_ANIMATION_WOLF_CROUCH 5
#define TR_ANIMATION_WOLF_START_RUN 6
#define TR_ANIMATION_WOLF_RUN 7
#define TR_ANIMATION_WOLF_STAY 8
#define TR_ANIMATION_WOLF_JUMP_ATTACK 9
#define TR_ANIMATION_WOLF_STAY_CROUCH 14
#define TR_ANIMATION_WOLF_WOOOO 16
#define TR_ANIMATION_WOLF_RUN_LEFT 18
#define TR_ANIMATION_WOLF_DEAD1 20
#define TR_ANIMATION_WOLF_DEAD2 21
#define TR_ANIMATION_WOLF_DEAD3 22

//   ====== WOLF'S STATES ======
#define TR_STATE_WOLF_STAY 1    // -> 2 -> 7 -> 8 -> 9
#define TR_STATE_WOLF_WALK 2    // -> 1 -> 5
#define TR_STATE_WOLF_RUN 3     // -> 6 -> 9 -> 10
#define TR_STATE_WOLF_CROUCH 5  // -> 3 -> 9 -> 12
#define TR_STATE_WOLF_JUMP_ATTACK 6   // -> 3
#define TR_STATE_WOLF_WOOOO 7
#define TR_STATE_WOLF_IDLE 8    // -> 1
#define TR_STATE_WOLF_STAY_CROUCH 9 // -> 1 -> 3 -> 5 -> 7 -> 12
#define TR_STATE_WOLF_RUN_RIGHT 10
#define TR_STATE_WOLF_DEAD 11
#define TR_STATE_WOLF_STAY_ATTACK 12

#endif

