
#ifndef STATE_CONTROL_RAPTOR_H
#define STATE_CONTROL_RAPTOR_H

/*
 *  ====== RAPTOR'S ANIMATIONS ======
 */
#define TR_ANIMATION_RAPTOR_STAY 0
#define TR_ANIMATION_RAPTOR_RUN 1
#define TR_ANIMATION_RAPTOR_ARRRR 4
#define TR_ANIMATION_RAPTOR_WALK 5
#define TR_ANIMATION_RAPTOR_RUN_ATTACK 8
#define TR_ANIMATION_RAPTOR_DEAD1 9
#define TR_ANIMATION_RAPTOR_DEAD2 10

//   ====== RAPTOR'S STATES ======
#define TR_STATE_RAPTOR_DEAD 0
#define TR_STATE_RAPTOR_STAY 1  // -> 2 -> 3 -> 4 -> 6 -> 8
#define TR_STATE_RAPTOR_WALK 2  // -> 1
#define TR_STATE_RAPTOR_RUN 3   // -> 1 -> 7
#define TR_STATE_RAPTOR_JUMP_ATTACK 4
#define TR_STATE_RAPTOR_ARRRR 6
#define TR_STATE_RAPTOR_RUN_ATTACK 7
#define TR_STATE_RAPTOR_STAY_ATTACK 8

#endif

