
#ifndef STATE_CONTROL_TORSO_BOSS_H
#define STATE_CONTROL_TORSO_BOSS_H

/*
 *  ====== PUMA'S ANIMATIONS ======
 */
#define TR_ANIMATION_TORSO_BOSS_INIT 0
#define TR_ANIMATION_TORSO_BOSS_STAY 2
#define TR_ANIMATION_TORSO_BOSS_DEAD 13

//   ====== PUMA'S STATES ======
#define TR_STATE_TORSO_BOSS_DEAD 0
#define TR_STATE_TORSO_BOSS_STAY 1  // -> 2 -> 3 -> 4 -> 5 -> 6 -> 7
#define TR_STATE_TORSO_BOSS_TURN_RIGHT 2 // -> 1
#define TR_STATE_TORSO_BOSS_TURN_LEFT 3 // -> 1
#define TR_STATE_TORSO_BOSS_ATTACK 4
#define TR_STATE_TORSO_BOSS_ATTACK_BIG 5
#define TR_STATE_TORSO_BOSS_ATTACK_KILL 6
#define TR_STATE_TORSO_BOSS_MOVE 7
#define TR_STATE_TORSO_BOSS_WTF 8
#define TR_STATE_TORSO_BOSS_ATTACK_JUMP 8
#define TR_STATE_TORSO_BOSS_FALL 9 // -> 1

#define TR_STATE_TORSO_BOSS_KILL 11

#endif

