#pragma once

//   ====== ANIMATION COMMANDS ======

#define TR_ANIMCOMMAND_SETPOSITION  1
#define TR_ANIMCOMMAND_SETVELOCITY  2
#define TR_ANIMCOMMAND_EMPTYHANDS   3
#define TR_ANIMCOMMAND_KILL         4
#define TR_ANIMCOMMAND_PLAYSOUND    5
#define TR_ANIMCOMMAND_PLAYEFFECT   6
#define TR_ANIMCOMMAND_INTERACT     7

//   ====== ANIMATION EFFECTS FLAGS ======

#define TR_ANIMCOMMAND_CONDITION_LAND  0x4000
#define TR_ANIMCOMMAND_CONDITION_WATER 0X8000
